### PR TITLE
initial PR

### PR DESCRIPTION
**Pull request by mfds**
moved package
removed `while`, `include` and `raw include` commands 

todo: gradle file, remove loaders

### CODE REVIEW

**Comment by badlogic** [comment]
???

**Comment by mfds** [comment]
Sorry, my bad. I’m forking your project but I was making a PR to the wrong fork.

Please disregard this.
M.

**Comment by badlogic** [comment]
This is so intriguing! Where you task to create a scripting language for Gospel? :D

**Comment by mfds** [comment]
Hey, glad you're interested. We just need a really simple template engine for something we're doing but I'm afraid that's all I can say :)

Regards

**Comment by badlogic** [comment]
Cool, make sure to retain the LICENSE :)

**Comment by mfds** [comment]
Absolutely. Take care

**Pull request closed without merging**
